% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{fontspec}
\usepackage{multirow}
\usepackage{multicol}
\usepackage{colortbl}
\usepackage{hhline}
\newlength\Oldarrayrulewidth
\newlength\Oldtabcolsep
\usepackage{longtable}
\usepackage{array}
\usepackage{hyperref}
\usepackage{float}
\usepackage{wrapfig}
\KOMAoption{captions}{tableheading}
\makeatletter
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[many]{tcolorbox}}
\makeatother
\makeatletter
\@ifundefined{shadecolor}{\definecolor{shadecolor}{rgb}{.97, .97, .97}}
\makeatother
\makeatletter
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={How Beauty Trumps Performance: An Examination of Instructor Evaluations at the University of Texas},
  pdfauthor={Marcin Jaczynski},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{How Beauty Trumps Performance: An Examination of Instructor
Evaluations at the University of Texas\thanks{Code and data are
available at: https://github.com/jackchinski/instructor-ratings}}
\author{Marcin Jaczynski}
\date{20 April 2023}

\begin{document}
\maketitle
\begin{abstract}
At the end of each semester of school, students are able to rate their
professors and teachers through course evaluations. However, there are
concerns about the validity and reliability of these evaluations as a
measure of teaching effectiveness. This paper examines the impact of
instructor beauty on course evaluations at the University of Texas
between 2000 and 2002, while also considering other factors that may
influence ratings. The findings suggest that beauty does have a positive
effect on evaluations, as such the use of the instructor evaluations for
the use of hiring, firing, and promoting instructors remains
controversial.
\end{abstract}
\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[frame hidden, borderline west={3pt}{0pt}{shadecolor}, interior hidden, boxrule=0pt, breakable, enhanced, sharp corners]}{\end{tcolorbox}}\fi

\hypertarget{introduction}{%
\subsection{1 Introduction}\label{introduction}}

Instructor ratings have a direct impact on the validity of an instructor
or professor, and may be used for hiring, firing, promotion and
consideration for tenure purposes. However, if beauty directly
influences the instructor's evaluation, then such a metric is not a fair
representation of the instructor, and therefore should be omitted in
considerations for promotions, firing and tenure. While there are a lot
of factors that play into how students will perceive an instructor and
what kind of rating they will give them at the end of the semester, one
that is not taken into consideration many times is how beautiful they
are. As such, I have chosen to try and answer ``How does an instructors
beauty, according to their students, affect the instructors course
evaluation?'' This paper seeks to examine what the trends in instructor
evaluations are from the students at the University of Texas during the
years 2000-2002. Among beauty, things such as age, gender, department,
tenure, and how many students they were teaching are going to be taken
into account and evaluated. Based on the observations from the 463
instructors, there is a correlation between the beauty of the instructor
and the evaluation they have received. These results have important
implications for how we understand the factors that shape student
perceptions of instructors and how we evaluate instructor performance.
The correlation between beauty and evaluation is not strong, and does
not persist when separating male and female instructors, where males
average a higher evaluation yet score lower in terms of beauty than
females. However, other things such as being native, and the class size
also have an impact on the overall evaluation of the instructor. This
paper will elaborate on the data, how it was sourced and analyzed, then
will explore the results, and discuss them as well as their limitations.

\hypertarget{data}{%
\subsection{2 Data}\label{data}}

\hypertarget{data-source-and-methodology}{%
\section{2.1 Data Source and
Methodology}\label{data-source-and-methodology}}

The data collected for this paper, was sourced form an Applied
Econmetrics with R (AER) library. The AER is a collection of data sets
in applied econometrics research, and is widely used in the academic
fields of empirical analysis of microeconomic data. The package is free
to download from the Comprehensive R Archive Network (CRAN), or can be
installed using the RConsole or RStudio.

\hypertarget{data-collection}{%
\section{2.2 Data Collection}\label{data-collection}}

The data set used in this paper contains data pertaining to course,
instructor and student evaluation data of 463 instructors. The data was
collected from the 2000-2002 academic years at the University of Texas
at Austin. The data was provided by Prof.~Hamermesh, and includes the
students ratings of their instructors as well as their beauty rating
(average from six independent judges), as well as other charasteristics
pertaining to the instructor. The details for the data collection
methodology of the TeachingRatings data set are unclear. However,
assumptions can be made that the data was collected through anonymous
teacher ratings websites such as rateMyProfessor.com or course
evaluations that were done at the school. However, the exact methodology
is not explicitly mentioned in the documentation of the data set or the
academic literature which uses the following data set.

The data set has been previously cleaned, and so it does not require any
additional cleaning, however, minor adjustments have been made, such as
omitting the columns ``\ldots1'' and ``prof'' as both of them only
contained the entry number, which was already present in data frame.
Additionally, as a safety check, a function was ran in order to remove
any N/A values, however, the result showed that no entries were removed
as a result of said function.

Each entry in the following data set contains the following details:

\begin{itemize}
\tightlist
\item
  Minority - factor. Does the instructor belong to a minority
  (non-Caucasian)?
\item
  Age - the professor's age.
\item
  Gender - factor indicating instructor's gender.
\item
  Credits - factor. Is the course a single-credit elective (e.g., yoga,
  aerobics, dance)?
\item
  Beauty - rating of the instructor's physical appearance by a panel of
  six students, averaged across the six * panelists, shifted to have a
  mean of zero. On a scale of -2.0 to 2.0.
\item
  Eval - course overall teaching evaluation score, on a scale of 1 (very
  unsatisfactory) to 5 (excellent).
\item
  Division - factor. Is the course an upper or lower division course?
  (Lower division courses are mainly large freshman and sophomore
  courses)?
\item
  Native- factor. Is the instructor a native English speaker?
\item
  Tenure - factor. Is the instructor on tenure track?
\item
  Students - number of students that participated in the evaluation.
\item
  Allstudents - number of students enrolled in the course.
\item
  Prof - factor indicating instructor identifier.
\end{itemize}

\hypertarget{data-analysis}{%
\section{2.3 Data Analysis}\label{data-analysis}}

The data set from AER was gathered by installing the AER package
(Kleiber and Zeileis 2020) in the RStudio (Team 2021) console, and then
the package contents were extracted to only include the TeachingRatings
data set in the ``download\_data'' file under ``/scripts''. The data was
then analyzed using the R programming language (R Core Team 2022).
Additionally, the programming packages dplyr (Wickham et al. 2023) as
well as tidyverse (Wickham et al. 2019), and (Wickham and RStudio 2021)
were used to analyze the data, test and create graphs.

\hypertarget{advantages-and-disadvantages}{%
\section{2.4 Advantages and
Disadvantages}\label{advantages-and-disadvantages}}

The following data set has both some advantages and disadvantages. In
terms of advantages, the data set is really easy to obtain and use. It
is available online for free, and requires 3 steps in order to gather
the main TeachingRatings data set. The data set that is then obtained
has also already been cleaned, as such it does not require any
additional work other than picking which columns will be used.
Additionally, the documentation which is provided is very thoroughly
written, with each column explained and examples of how to install the
package and obtain the data. However, in terms of the disadvantages,
firstly the documentation that is provided, does not provide any
background context on the data gathering methodology, and if there was
any incentive to complete the survey. The data set also contains 463
entries, which over a two year span, does not seem like a large number
of entries. Additionally, the study was performed in the year 2002,
which would not qualify it as a recent study, and would likely need to
be redone to be applicable to more recent years, especially after a
global pandemic in the years 2020-2022.

\hypertarget{results}{%
\subsection{3 Results}\label{results}}

\hypertarget{male-vs.-female}{%
\section{3.1 Male vs.~Female}\label{male-vs.-female}}

The first area I explored, while trying to find what affected an
instructors evaluation is the gender of the instructor. According to my
initial hypothesis, if one gender scored a higher in beauty metrics ,
then they would also score higher in terms of evaluation. As such, I
decided to create two seperate graphs in order to show the correlation
between beauty and evaluation for both genders.
Figure~\ref{fig-males-beauty-eval} shows the beauty and evaluation
scores for all male instructors, and, the results show that for male
instructs for every additional point of beauty rating, we would expect
the evaluation to increase by c

\begin{figure}

{\centering \includegraphics{paper_files/figure-pdf/fig-males-beauty-eval-1.pdf}

}

\caption{\label{fig-males-beauty-eval}Beaty and Evaluation scores that
increase for male instructors by 0.20027.}

\end{figure}

The next Figure~\ref{fig-females-beauty-eval} explores the correlation
between the beauty and evaluation of female instructors. The figure
conforms to my hypothesis, as for every additional point in beauty
ratings the instructor should gain an extra 0.08762 evaluation points.

\begin{figure}

{\centering \includegraphics{paper_files/figure-pdf/fig-females-beauty-eval-1.pdf}

}

\caption{\label{fig-females-beauty-eval}Beaty and Evaluation scores that
increase for female instructors by 0.08762.}

\end{figure}

Figure~\ref{fig-females-beauty-eval-with-males-abline} shows the graph
of the beauty and evaluation correlation for female instructors with the
line of best fit for the male instructors. According to the models, for
men the beauty affects their evaluations more than the female
instructors.

\begin{figure}

{\centering \includegraphics{paper_files/figure-pdf/fig-females-beauty-eval-with-males-abline-1.pdf}

}

\caption{\label{fig-females-beauty-eval-with-males-abline}Female
instructors beauty and evaluation with the male and female line of best
fit}

\end{figure}

Table~\ref{tbl-avgmaleandfemalebeautyandeval} shows the average beauty
and evaluation rating for both males and females. After seeing the
results of the male instructors having their evaluation be affected more
by their beauty, I wanted to see what the average rating for both males
and females were. According to the data, male instructors have a lower
average beauty rating than female instructors, yet males are on average
more highly rated. After seeing the following results, I decided to take
on another route to figure out what impacted the instructors evaluation
the most.

\hypertarget{tbl-avgmaleandfemalebeautyandeval}{}
\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{0pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{0.79in}|p{1.14in}|p{0.92in}}

\caption{\label{tbl-avgmaleandfemalebeautyandeval}The average bveauty and ealuation for males and females. } \\ 


\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.79in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Gender}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.14in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Beauty}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.92in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Eval}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.79in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Male}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.14in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{-0.08448224}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.92in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{4.069030}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.79in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Female}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.14in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.11610907}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.92in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{3.901026}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

According to Figure~\ref{fig-overall-beauty-and-eval} there is a
correlation between the beauty of the instructor and their evaluation.
However, what had the biggest impact? The slope of the line for both
male and female instructors is 0.133, meaning that every increase in
beauty should yield an evaluation higher by 0.133. Additionally the
r\^{}2 value is 0.03364 or 3\% , indicating that evaluation can be
explained by the variability in beauty, which is the variability of y
that is explained by the x. The r\^{}2 indicates how much it affects the
evaluation.

\begin{figure}

{\centering \includegraphics{paper_files/figure-pdf/fig-overall-beauty-and-eval-1.pdf}

}

\caption{\label{fig-overall-beauty-and-eval}Overall correlation betwen
beauty and evaluation for all instructors, in green is the line of best
fit}

\end{figure}

Table~\ref{tbl-coefficients-affecting-eval} shows off all of the
coefficients and how they respectively affect the evaluation of the
instructor. The p-value is the indicator of how likely something is due
to pure randomness, and so a low p-value means that something is very
unlikely to be due to pure chance. For all of the variables that affect
the instructors evaluation, the p-value is 7.822e-15, which is really
small. This indicates that the variables present do in fact affect the
evaluation of an instructor, and there is a small chance that it is due
to randomness. The estimate shows how much each variable is able to
affect the evaluation of an instructor as it increases. The p-value for
each again indicates how likely it is that each variable could be
affecting the evaluation due to pure chance. Based on the data I use the
95\% rule to say that there is less than 5\% that the strong affecting
variables are not due to chance and they have a great impact, these
include: minority, gender, credits, beauty, native, students,
allstudents.

\hypertarget{tbl-coefficients-affecting-eval}{}
\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{0pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{1.19in}|p{1.23in}|p{1.29in}}

\caption{\label{tbl-coefficients-affecting-eval}All of the varaibles which affect evaluation, estimate tells us how much
evaluation will rise as does the variable, standard error describes how
likely it is that the variable affects the evaluation due to chance. } \\ 


\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Coefficient}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Estimate}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Standard\ Error}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{(Intercept)}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{3.801477582}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.185771339}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{minorityyes}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{-0.165221740}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.076515480}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{age}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{-0.002055879}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.002676510}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{gendermale}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.203477717}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.051443208}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{creditssingle}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.560532616}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.116679935}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{beauty}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.145758015}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.032194375}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{divisionupper}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{-0.044795193}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.056791711}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{nativeyes}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.235691233}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.106458510}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{tenureyes}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{-0.051233466}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.062578312}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{students}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.007426996}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.002300905}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{allstudents}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{-0.004626833}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.001396391}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

Table~\ref{tbl-strong-coefficients-affecting-eval} shows all of the
variables that affect an instructor's evaluation the most. The estimate
is how much the evaluation is how much the evaluation will either
increase or decrease based on the change in the variable, and the
p-value is how likely it is to be due to randomness.

\hypertarget{tbl-strong-coefficients-affecting-eval}{}
\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{0pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable}[c]{|p{1.19in}|p{1.23in}|p{1.29in}}

\caption{\label{tbl-strong-coefficients-affecting-eval}Strong coeffcients affecting the evalution of instructors } \\ 


\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Coefficient}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Estimate}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{Standard\ Error}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{(Intercept)}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{3.801477582}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.185771339}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{minorityyes}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{-0.165221740}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.076515480}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{age}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{-0.002055879}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.002676510}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{gendermale}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.203477717}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.051443208}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{creditssingle}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.560532616}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.116679935}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{beauty}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.145758015}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.032194375}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{divisionupper}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{-0.044795193}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.056791711}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{nativeyes}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.235691233}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.106458510}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{tenureyes}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{-0.051233466}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.062578312}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{students}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.007426996}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.002300905}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.19in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{allstudents}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.23in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{-0.004626833}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.29in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{0.001396391}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\hypertarget{discussion}{%
\subsection{4 Discussion}\label{discussion}}

\hypertarget{beauty-and-evaluation}{%
\section{4.1 Beauty and Evaluation}\label{beauty-and-evaluation}}

After reviewing all of the data, my initial hypothesis that beauty does
influence an instructor's evaluation stands true, as the data shows that
for each unit increase in beauty should result in a corresponding
increase in evaluation score of 0.16. However, other factors also play a
significant factor to the instructors evaluation.

\hypertarget{male-and-female-instructors}{%
\section{4.2 Male and Female
Instructors}\label{male-and-female-instructors}}

From the findings, it has been shown that female instructors receive
lower evaluations than male instructors, while holding all other
variables constant. The average female evaluation was 3.90, while the
average male evaluation was 4.07, despite females scoring higher in
terms of beauty than males. The difference is small, however
statistically significant, as it contradicts my hypothesis of higher
beauty leading to a higher evaluation. However, more data and research
would need to be done in order to explore the possible reasons, and see
if the trend continues.

\hypertarget{class-size}{%
\section{4.3 Class Size}\label{class-size}}

Another factor which affected the evaluation of instructors, was the
class size. The data shows that instructors who teach larger classes
receive higher evaluations, than those who teach smaller ones. However,
the following trend is seen to take less of an effect as class sizes
continue to increase. As such, there is a positive correlation between
the class size and evaluation, but this effect is limited. \# 4.4
Minorities Instructors who are minorities are seen to receive lower
evaluations than those who are not a minority. The data shows that
minority instructors received evaluations that are 0.16 units lower on
average than those instructors who are not a minority.

\hypertarget{native}{%
\section{4.5 Native}\label{native}}

Based on the data, instructors who are native receive lower evaluations
than those who are not. The coefficient estimate for ``nativeyes'' is
0.259451, meaning that being a native instructor would increase the
evaluation score by 0.259451 units, as compared to those who are non
native. This effect has a significant effect on the evaluation of the
instructors with a p-value of 0.013446. However, according to the data,
non-native instructors actually receive higher evaluations than their
native counterparts. This seems counter intuitive that while the
estimate is positive, they receive lower evaluations, however, the
estimate is holding all other variables constant which means that the
estimate is the difference in the evaluation is everything else about
two instructors remains identical. As such, though the estimate is
positive, the actual data shows that the native instructors actually
receive lower evaluations that the non-native instructors.

\hypertarget{limitations}{%
\subsection{5 Limitations}\label{limitations}}

There are several limitations to consider from the following study.
Firstly the study was conducted at one university, and therefore cannot
be a generalization of other universities or students. Additionally, the
study is relatively, old given by the fact that it was conducted in the
years 2000-20002, and cannot reflect the changes in student
demographics, teaching methodologies, and evaluation practices since
then. Additionally, the method of data collection is unknown, therefore
the reliability of the data is unknown. Moreover, the grading scale
which was used in the study ranges from -2.0 to 2.0 for measuring
beauty, which could potentially be unfamiliar to some and cause invalid
ratings. The measure of beauty in the study is also based on personal
preference of the students which were assessing the instructors beauty,
which cannot be a unified measurement, and would vary depending on which
students were chosen to evaluate the instructors beauty. This could
potentially introduce variability and bias in the study.

Going back to the results of the native instructors versus the
non-native ones. While the ``native-yes'' estimate is positive,
indicating that native instructors should receive a higher evaluation,
the actual data shows they receive a lower one. This means there could
be some hidden variables which have not been accounted for such as the
instructors language proficiency, that may also affect the students
evaluation of their instructors.

Lastly, the study lacks information about the students themselves which
carried out the evaluations. Cross referencing instructor evaluations to
student data such as their age, gender, academic performance could have
significant impact on the instructor. For example female students could
find a male instructor highly attractive, but if only 6 male students
were chosen to evaluate their beauty, then the data could be skewed.
Additionally, students which do well in a course are more likely to
review their instructor positively, while those who performed poorly
tend to leave more negative evaluations. Leaving an abnormally negative
score, could lead to the results being inaccurate, and without said
information it is hard to understand the factors which influence an
instructor's evaluation.

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-AER}{}}%
Kleiber, Christian, and Achim Zeileis. 2020. \emph{Applied Econometrics
with r}. \url{https://cran.r-project.org/package=AER}.

\leavevmode\vadjust pre{\hypertarget{ref-rcoreteam2022}{}}%
R Core Team. 2022. \emph{R: A Language and Environment for Statistical
Computing}. Vienna, Austria: R Foundation for Statistical Computing.
\url{https://www.R-project.org/}.

\leavevmode\vadjust pre{\hypertarget{ref-rstudio}{}}%
Team, RStudio. 2021. \emph{{RStudio}: Integrated Development Environment
for r}. Boston, MA: RStudio, PBC. \url{https://www.rstudio.com}.

\leavevmode\vadjust pre{\hypertarget{ref-wickham2019}{}}%
Wickham, Hadley, Mara Averick, Jennifer Bryan, Winston Chang, Lucy
D'Agostino McGowan, Romain François, Garrett Grolemund, et al. 2019.
\emph{Welcome to the {tidyverse}}. \emph{Journal of Open Source
Software}. Vol. 4. \url{https://doi.org/10.21105/joss.01686}.

\leavevmode\vadjust pre{\hypertarget{ref-wickham2023}{}}%
Wickham, Hadley, Romain François, Lionel Henry, Kirill Müller, and Davis
Vaughan. 2023. \emph{Dplyr: A Grammar of Data Manipulation}.

\leavevmode\vadjust pre{\hypertarget{ref-testthat}{}}%
Wickham, Hadley, and RStudio. 2021. \emph{Testthat: Get Started with
Testing}. \url{https://testthat.r-lib.org/}.

\end{CSLReferences}



\end{document}
